# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 15
    rebase-strategy: 'auto'
    schedule:
      interval: 'weekly'
    groups:
      material-ui:
        patterns:
          - '@emotion/*'
          - '@mui/*'
        exclude-patterns:
          - '@mui/x-date-pickers'
      luxon:
        patterns:
          - 'luxon'
          - '@types/luxon'
      development-dependencies:
        dependency-type: 'development'
      production-dependencies:
        dependency-type: 'production'
        exclude-patterns:
          - '@emotion/*'
          - '@mui/*'
          - 'luxon'
          - '@types/luxon'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'docker'
    directory: /
    open-pull-requests-limit: 15
    rebase-strategy: 'auto'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 15
    rebase-strategy: 'auto'
    schedule:
      interval: 'weekly'
