/*
 * Copyright 2024 Nordeck IT + Consulting GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/Auth/AuthProvider";
import { LocalizationProvider } from "@/utils/localization/LocalizationProvider";
import { SnackbarProvider } from "@/contexts/Snackbar/SnackbarContext";
import { SessionProvider } from "@/contexts/Session/SessionContext";
import "../../i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html>
      <body className={inter.className}>
        <LocalizationProvider>
          <SnackbarProvider>
            <SessionProvider>
              <AuthProvider>{children}</AuthProvider>
            </SessionProvider>
          </SnackbarProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
